[package]
name = "shvdevice-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "shvdevice"
path = "src/lib.rs"

[[bin]]
name = "simple_device"
path = "src/examples/simple_device.rs"

[dependencies]
shv = { git = "https://github.com/j4r0u53k/shv-rs.git", branch = "use-into-target-in-interfaces" }
futures = "0.3.29"
# async-std = { version = "1.12.0", features = ["attributes"] }
url = "2.4.1"
clap = { version = "4.4.12", features = ["derive"] }
log = "0.4.20"
simple_logger = { git = "https://github.com/fvacek/rust-simple_logger.git", branch = "main", features = ["stderr"] }
duration-str = "0.7.1"
async-broadcast = "0.6.0"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
